name: book_manager
description: A book management app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  firebase_auth_web: ^5.8.10  # Or match to what firebase_auth 4.17.0 expects
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_hooks: ^0.18.6
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  uuid: ^3.0.7
  http: ^0.13.6
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  syncfusion_flutter_datagrid: ^23.1.39
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png